server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api
  datasource:
    url: jdbc:h2:mem:alert-service;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa

  h2:
    console:
      path: /h2console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  data:
    redis:
      port: 6379
      host: test-redis
      password: 1234
  sql:
    init:
      mode: always

